name: ecommerce_application
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'






# -------------------- PACKAGES ------------------- #
dependencies:
  flutter:
    sdk: flutter

 # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  hive: ^2.2.3
  get_it: ^7.6.7
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.5
  path_provider:
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  flutter_screenutil:
  font_awesome_flutter: ^10.7.0




  # -------------------- ./ PACKAGES END ------------------- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/logos/GardeniaWhite.png
  image_dark: assets/logos/GardeniaDark.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: assets/logos/GardeniaWhite.png
    image_dark: assets/logos/GardeniaDark.png


  web: false
  
  
  
  
flutter_lints: ^2.0.0





flutter:

  uses-material-design: true
  # -------------------- LOCAL ASSETS ------------------- #
  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


